- id: '1593364811767'
  alias: Jo medication reminder
  description: ''
  trigger:
  - at: '11:00:00'
    platform: time
  - at: '17:00:00'
    platform: time
  - at: '23:00:00'
    platform: time
  condition: []
  action:
  - data:
      message: '{{ ["Jo, it''s time for your tablet",  "Don''t forget to take your
        tablet, Jo", "Jo, if you haven''t already taken your tablet, its time to take
        it now", "Remember to take your tablet, Jo" ] | random }}'
    service: notify.broadcast_from_home_assistant
- id: '1601999861619'
  alias: Emma Chore reminder
  description: ''
  trigger:
  - platform: time
    at: '16:00:00'
  condition:
  - condition: time
    weekday:
    - mon
    - fri
  action:
  - service: notify.mobile_app_emma_s_phone
    data:
      message: Take out recycling today!
      title: Recycling day
      data:
        color: red
        tag: recycling
        sticky: true
  mode: single
