plex_assistant:
  url: 'http://192.168.1.3:32400'
  token: !secret plex_token
  default_cast: 'Downstairs TV'
  language: 'en'
  tts_errors: true
  aliases:
    Downstairs TV: ib13ap7t27ka007jzq4r4n30
    Jennys Phone: c34af2d6056237cc-com-plexapp-android

sensor:
  - platform: plex_assistant
