sensor:
  - platform: history_stats
    name: Emma's Screen Time Today
    entity_id: binary_sensor.emma_s_phone_interactive
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0, minute=0, second=0) }}'
    end: '{{ now() }}'

  - platform: history_stats
    name: Emma's Screen Time This week
    entity_id: binary_sensor.emma_s_phone_interactive
    state: 'on'
    type: time
    start: '{{ as_timestamp( now().replace(hour=0, minute=0, second=0) ) - now().weekday() * 86400 }}'
    end: '{{ now() }}'
