sensor:
  - platform: youtube
    channel_id: UCSC1HqVmTaE4Shn32ihbC7w

  - platform: socialblade
    name: bobby_duke_arts_info
    channel_id: UCSC1HqVmTaE4Shn32ihbC7w

automation:
  - id: 'd44e80dd-7494-4735-b3cd-24bd4c59241c'
    alias: YouTube Notification - Bobby Duke Arts
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.bobby_duke_arts
        attribute: url
    action:
      - service: notify.mobile_app_jenny_s_oppo_reno
        data:
          message: '{{ states("sensor.bobby_duke_arts")}}'
          title: >
            {% if is_state_attr("sensor.bobby_duke_arts", "live", False) -%}
            'New Bobby Duke Video Available'
            {%- else -%}
            'Bobby Duke is Live!'
            {%- endif %}
          data:
            image: "{{state_attr('sensor.bobby_duke_arts','entity_picture')}}"
            tag: bobby_duke_arts
            color: 'green'
            actions:
              - action: "URI"
                title: "Watch Now"
                uri: '{{ state_attr("sensor.bobby_duke_arts","url") }}'
      - delay:
          seconds: 300
