sensor:
  - platform: youtube
    channel_id: UC301G8JJFzY0BZ_0lshpKpQ

  - platform: socialblade
    name: vcloudinfo_info
    channel_id: UC301G8JJFzY0BZ_0lshpKpQ

automation:
  - id: '3b2e2907-c067-4678-9725-482250d9b43c'
    alias: YouTube Notification - vCloudInfo
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.vcloudinfo
        attribute: url
    action:
      - service: notify.mobile_app_jenny_s_oppo_reno
        data:
          message: '{{ states("sensor.vcloudinfo")}}'
          title: >
            {% if is_state_attr("sensor.vcloudinfo", "live", False) -%}
            'New vCloudInfo Video Available'
            {%- else -%}
            'vCloudInfo is Live!'
            {%- endif %}
          data:
            image: "{{state_attr('sensor.vcloudinfo','entity_picture')}}"
            tag: vcloudinfo
            color: 'green'
            actions:
              - action: "URI"
                title: "Watch Now"
                uri: '{{ state_attr("sensor.vcloudinfo","url") }}'
      - delay:
          seconds: 300
