substitutions:
  devicename: sitting_room_wall_light_shelly1
  friendly_name: Sitting Room Wall Lights
  $reboot_time: 0s
  ip_address: 192.168.1.19

packages:
  device_base: !include common/shelly1_light.yaml
